# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWDmB7v8kMpJKAjft3F2XrFgqhQtuOgO
"""



import streamlit as st

# Functions for the calculator operations
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Error! Division by zero."
    else:
        return x / y

# Streamlit interface
def calculator():
    st.title("Basic Calculator")

    # Take input from user
    num1 = st.number_input("Enter first number:", value=0.0)
    num2 = st.number_input("Enter second number:", value=0.0)

    operation = st.radio("Choose operation:", ("Add", "Subtract", "Multiply", "Divide"))

    # Perform the operation and display result
    if operation == "Add":
        result = add(num1, num2)
        st.write(f"The result of {num1} + {num2} is {result}")
    elif operation == "Subtract":
        result = subtract(num1, num2)
        st.write(f"The result of {num1} - {num2} is {result}")
    elif operation == "Multiply":
        result = multiply(num1, num2)
        st.write(f"The result of {num1} * {num2} is {result}")
    elif operation == "Divide":
        result = divide(num1, num2)
        st.write(f"The result of {num1} / {num2} is {result}")

# Run the calculator app
if __name__ == "__main__":
    calculator()

